### ISSUE TITLE
Introduce yourself

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/e15-spring20#1]
Hi everyone - 

I thought I'd kick off a post where everyone can reply with an introduction to themselves so we can get to know each other. 

**Tell us what brought you to this course and any other details you care to share.**

A little bit about myself - I'm a web programmer and educator, living in Arlington, MA. In addition to this course, I also teach [DGMD E-2](/e2) and [CSCI E-15](https://hesweb.dev/e15). I've also worked with students completing their capstones in the DGMD program.

In the past, I've taught at Wellesley, UPenn, and UMiami. When working in industry I was the head developer for an online e-commerce store. 

More about my background here: [susanbuck.net](https://susanbuck.net)

All in all, I love creating things with code and teaching others how to do the same.

Looking forward to getting to know you all!

**Comment by RGPhD** [comment]
Hello Professor Susan Buck and Classmates,

I am very excited and anxious for this PHP Laravel course because I am fairly new to frameworks.  I have only used the E-2 framework from the PHP beginner class <https://hesweb.dev/e2>.  Nonetheless, I am taking this class as a candidate for the Masters of Liberal Arts in Digital Media Design at Harvard Extension School (HES).  I will also finish my Web Technologies Certificate at HES this semester.  

Further, HES’s online classes fit very well into my hectic schedule.  I am currently an Arizona State University (ASU) Faculty Affiliate in Biomimicry, a Professor at Personal Professors Online Academy and I periodically teach undergraduate courses for ASU.  Additionally, I teach American Red Cross, lifestyle medicine, geriatric wellness, health and biogerontology kinesiology classes online and in person at Senior University.

My previous education is as diverse as my current teaching.  I just completed my fourth diploma at ASU (2019), a Graduate Certificate in Law Enforcement Administration.  I am also ABD away from my second Doctorate, the Doctor of Behavioral Health degree.  Moreover, I completed a Master of Arts in Criminal Justice and Criminology in 2014, a Master of Science in Aging and Lifespan Development in 2011 and a Post-Doc Graduate Certificate in Gerontology in 2009.  In addition, I have a PhD and MEd in Education/Athletic Administration and a Master of Science in Kinesiology that I finished in the 90's.  I am also working on a Doctor of Metaphysics at The University of Sedona. 

What started as an avenue to participation in collegiate athletics has turned into my life’s passion as a *Lifelong Learner and Lifelong Educator*.  After retiring as a professional basketball player and tenured professor, I began my pursuit to becoming a Multidisciplinary Educator and Interdisciplinary Scholar.  When I am not teaching or studying, I love to stay busy volunteering.  I started volunteering for Harvard University DCE Accessibility Services my first semester at HES.

I currently reside in North Scottsdale, Arizona.  **I look forward to learning with and from all of you in the GitHub forums!**

Robelyn

**Comment by kreinholz** [comment]
Greetings, everyone!

I took [DGMD E-28](https://hesweb.dev/e28/) last semester and really enjoyed it, so here I am back for more! This is my final course toward a **Web Technologies Certificate**--in addition to last semester's course with Professor Buck, I've taken [CSCI E-3](https://canvas.harvard.edu/courses/8478/assignments/syllabus), [CSCI E-31](https://www.extension.harvard.edu/course-catalog/courses/web-application-development-using-nodejs/25038), and [CSCI E-33a](https://cs50.harvard.edu/extension/web/2020/spring/). I also took [CS-50](https://cs50.harvard.edu/college/2020/spring/) many moons ago, when it incorporated PHP the last few weeks instead of Python like it does now.

I live and work in Southern California, in Riverside County (north of San Diego). I'm a retired Air Force officer and have my attorney's license, although currently I'm working in Human Resources for the federal government. I'd eventually like to transition to a career in web/software development, but for right now I'm just enjoying learning server and client side programming in my spare time with an eye toward working on some personal projects and possibly building up a portfolio of work product samples, and potentially doing some freelance web development work on the side before taking the big plunge into a new career.

I look forward to an interesting and productive semester with all of you!

Kevin

**Comment by janenycxo** [comment]
HI Professor Susan Buck,

I live in Queens, NY and this is my final semester (taking the last 3 courses) towards the IS Masters.  I had a great experience in your course last semester, so I am looking forward to another great semester. Github has been a helpful forum!

Cheers!
Jane

**Comment by RGPhD** [comment]
Nice to see you again Jane @janenycxo :)

Nice to virtually meet you Kevin @kreinholz.  I am also finishing my  **Web Technologies Cert** this semester, if all goes well ;)   I have thought about taking the *CS-50* course this summer as an elective, but not sure if it is too intense for a 7-week class.  I read that it is the largest course at Harvard, as far as campus wide enrollment.

Hope you guys have a great semester,
Robelyn

**Comment by kreinholz** [comment]
@RGPhD 

CS-50 is an introductory computer science course, so I’m not sure how much you’ll get out of it. When I took it back in 2012, I had zero prior CS experience. The class literally started out with Scratch, teaching the basic concepts of programming, then moved on to C, which we spent the majority of the semester on. It’s not the most forgiving language but it was informative. Then at the very end we spent a few weeks on PHP, but I understand they now spend that time on Python/Flask.

The pacing was very quick, and I spent 20+ hours per week on the coursework during the semester-long version of the class. We also had 2 pen and paper exams, but I’m not sure if they still do that. The exams were very hard. The class was intense, but it was a lot of fun, too, and I enjoyed it. It’s just a question of having the time and energy to commit to it.

If you want to get more of an “intensive introduction” to computer science and algorithmic thinking, it’s a great course. Since you’ve already taken E-2, and are now taking E-15, I don’t imagine you would *need* an introduction to for loops, conditionals, and variables/arrays/objects, but we can always stand to hone our understanding of the basics. I do remember they offered advanced versions of the problem sets for students who felt “more comfortable” with the material so you could probably still get a challenge out of the course even having some prior programming experience.

It was a fun experience, and if you have the time and energy to spare, I say go for it. I certainly enjoyed it, and it’s actually the reason I started taking CS classes through HES again in Fall 2018.

**Comment by RGPhD** [comment]
Hi Kevin @kreinholz,

Thank you very much for the info on 💻 **CS-50**.

Robelyn

**Comment by nicholsonjf** [comment]
Hi everyone,

My name is James Nicholson, this is my first HES course. I'm taking this as a graduate level course and am interested in pursuing the Master's in Software Engineering here. Currently I'm working as a Senior Web and Application Developer at the Harvard Chan School of Public Health. We use PHP and Laravel heavily so this course could not be more relevant to my role. I look forward to learning and programming alongside you.

James

**Comment by nnoel2626** [comment]
I have taken the DWA-E15 Dynamic Web Applications class about five ago. At the time, web development technology was using the traditional approach where the server was not only responsible to fetch the requested data but also responsible to provide a full response package that included HTML CSS and javascript that got rendered in the browser. Newer frameworks like Angular, Vue.Js etc.. made it possible to adopt this single page or hybrid web architecture approach.
Also, I recently took the DGMD-E28 class with Susan then I realized that I needed a better understanding of the functionality of the backend Sever such as Laravel. Hence, I decided to retake the updated version of this class which is now called CSCI E-15 Web Server Frameworks with Laravel/PHP. I look forward to work with all of you.

**Comment by kreinholz** [comment]
@nnoel2626 that sounds like a great reason for taking this class!

If you're interested in the server side of things, CSCI E-31 is another great class, but I have to admit, while a Node.js/Express server is extremely versatile and unopinionated, the sheer amount of freedom can be frustrating, especially when it comes to solving common design problems (and feeling like I'm needlessly reinventing the wheel). I found Python's Django framework to be _much_ easier for setting up an out-of-the-box web server with integrated database support. (Although I have a preference for NoSQL databases like MongoDB, which Django doesn't play so nice with).

I'm actually extremely curious how PHP/Laravel compares to Node.js/Express on the one extreme, and Python/Django on the other. I'm guessing (hoping) it falls somewhere in the middle. PHP is also so prolific on the web that it seems like a good skill to know/brush up on. Odds are, no matter how much other server frameworks are _the next big thing_, PHP will be around for a long time to come yet.

**Comment by cjreilly** [comment]
Hello CSCI E-97,

I am taking this class for graduate credit. I have programming experience and much of it is working with web frameworks. I haven't used PHP in some time so this will be a good refresher for me.

**Comment by ra1101** [comment]
Hello everyone

I took DGMD-E28 last term as well as a few others here, and thought it was a great course.  I haven't worked much with frontend web technology, so this pair of courses seems to be a great introduction.

Ray

**Comment by anyav77** [comment]
> Hello Professor Susan Buck and Classmates,
> 
> I am very excited and anxious for this PHP Laravel course because I am fairly new to frameworks. I have only used the E-2 framework from the PHP beginner class https://hesweb.dev/e2. Nonetheless, I am taking this class as a candidate for the Masters of Liberal Arts in Digital Media Design at Harvard Extension School (HES). I will also finish my Web Technologies Certificate at HES this semester.
> 
> Further, HES’s online classes fit very well into my hectic schedule. I am currently an Arizona State University (ASU) Faculty Affiliate in Biomimicry, a Professor at Personal Professors Online Academy and I periodically teach undergraduate courses for ASU. Additionally, I teach American Red Cross, lifestyle medicine, geriatric wellness, health and biogerontology kinesiology classes online and in person at Senior University.
> 
> My previous education is as diverse as my current teaching. I just completed my fourth diploma at ASU (2019), a Graduate Certificate in Law Enforcement Administration. I am also ABD away from my second Doctorate, the Doctor of Behavioral Health degree. Moreover, I completed a Master of Arts in Criminal Justice and Criminology in 2014, a Master of Science in Aging and Lifespan Development in 2011 and a Post-Doc Graduate Certificate in Gerontology in 2009. In addition, I have a PhD and MEd in Education/Athletic Administration and a Master of Science in Kinesiology that I finished in the 90's. I am also working on a Doctor of Metaphysics at The University of Sedona.
> 
> What started as an avenue to participation in collegiate athletics has turned into my life’s passion as a _Lifelong Learner and Lifelong Educator_. After retiring as a professional basketball player and tenured professor, I began my pursuit to becoming a Multidisciplinary Educator and Interdisciplinary Scholar. When I am not teaching or studying, I love to stay busy volunteering. I started volunteering for Harvard University DCE Accessibility Services my first semester at HES.
> 
> I currently reside in North Scottsdale, Arizona. **I look forward to learning with and from all of you in the GitHub forums!**
> 
> Robelyn

Nice to see you again!

**Comment by anyav77** [comment]
> @RGPhD

@RGPhD and @kreinholz  
I've also thought of CSCI-50 and being intimidated.  As an option, it's offered through self-paced edX.  I'm considering this self-paced option in the winter term.

**Comment by anyav77** [comment]
Hi everyone,

I'm a newly admitted degree candidate in HES Digital Media Design.  Last semester, I graduated with Web Technology Certificate, and I took DGMD E-2 as the last course toward the certificate.
I also started to work on the Back-End Web Programming Certificate.
I'm hoping to build a dynamic media website as my thesis, and I'm exploring the technology options.
DGMD E-28 and CSCI E-31 sound very interesting.  Thank you for sharing the information, @kreinholz and @nnoel2626

@susanBuck
Prof. Susan Buck, please let me know if you have any future classes/technology suggestions.  I will need functionality similar to Wikipedia, some e-Commerce and searching media/LTI (Youtube-like).
It sounds like a lot, and I understand that I may need to chunk it in pieces.

I look forward to learning Lavarel and starting on Wiki soon!

Anya

**Comment by RGPhD** [comment]
Dear Anya @anyav77,

It is nice to see you in class again also.  I will check my LinkedIn :)

I have been thinking of taking the self-paced version of **CS-50 edX** prior to taking the for credit version, just for the extra practice.  I see the edX version is 11 weeks, the Harvard EXT version is 15 weeks, and the Harvard summer school version is 7 weeks.  Let me know what you decide.

Kind regards,
Robelyn

**Comment by kreinholz** [comment]
@anyav77 

Out of curiosity, do you think the Web Technologies Certificate or the Back-End Web Development certificate is more valuable?

I checked my HES account and, assuming I passing this class with at least a "B", I qualify for my choice of the Front-End Web Development certificate, the Back-End Web Development Certificate, or the Web Technologies Certificate.

I was thinking I'd just get the Web Technologies Certificate since it takes 5 courses instead of 4, but it's more generic than the other 2... Any thoughts?

Welcome to the class!

**Comment by RGPhD** [comment]
Hello @kreinholz Kevin,

IMO, I believe the *Web Technologies Certificate* is of more value.  One, because it is considered **Full-Stack** and two because it will notate on your Cert that it is a Professional Graduate Certificate 5 course (20 credit hour) certification rather than a 4 course.  But, I also think any of the three are a valuable addition to a resumé.

<https://www.extension.harvard.edu/resources-policies/requesting-your-certificate>

Robelyn

**Comment by kreinholz** [comment]
@RGPhD thanks for that. My concern was that _Web Technologies_ can be a little more generic/light on programming, but it remains my default since it's 5 courses instead of 4. I suppose it's the specific courses we take, and not the name of the certificate, that will be valued greater.

Kevin

**Comment by budostylz** [comment]
Hello everyone, I know I am late and this post is close.  My name is Shaun and currently taking this course to improve my skill sets as a web/software developer. Professionally I am a web developer currently specializing in building SharePoint applications(a CMS like WordPress but heavily used within the government/military sector). On the military side I am an IT specialist for the Army Reserves(which explains my late post since completing the 2-week annual training requirement). Looking forward to taking this course and working with everyone. So far this course is great and having fun practicing the concepts and learning from a great instructor like Susan.

**Comment by kreinholz** [comment]
Welcome @budostylz Shaun! I'm retired Air Force and I know all too well our obsession with SharePoint! Hope you enjoy the course and get a lot out of it.
