### ISSUE TITLE
How to reload browser page

### ISSUE THREAD

**Issue by nnoel2626** [susanBuck/e15-spring20#10]
I would like to add a reset button after users input their string. Is there a way to reload the page in PHP or do I have to use javascript?

**Comment by RGPhD** [comment]
Hi Norcius Noel @nnoel2626,

For these smaller apps you can use a link to your original page or a reset submit button to your original URL (not the index.php path in browser).  Alternatively, you could just instruct the visitor to refresh the page if you are using **POST**.  

I used ```window.location.reload()``` in my view file for p1.  This option refreshes with the index.php version of my p1.  I guess it depends on where you want the page to reload for the visitor and whether you are using **GET** or **POST** and if you have ended your **SESSION** or at least have set results to null.

Robelyn

**Comment by budostylz** [comment]
When reloading a page, I like to handle this on the front end due to the specs of this project. As Robelyn stated, window.location.reload() is a good approach. There are some use cases however, where some web pages exhibit recursive behavior(web page never stops reloading) when using JavaScript reload functions. Let us know if you are experiencing this and we can find alternatives.

**Comment by nnoel2626** [comment]
Thank you so much Robelyn and Shaun for the help.
I also found that using a button link also does the trick:
```php
"location.href='index.php'"
```

**Comment by susanBuck** [comment]
👍to @RGPhD and @budostylz's suggestions, and also the ultimate solution you landed on @nnoel2626.
