### ISSUE TITLE
Unable to pass variables to form view

### ISSUE THREAD

**Issue by nnoel2626** [susanBuck/e15-spring20#22]
**In this  controller method below:**

```PHP
  public function splitTotal()
    {
        # Check to see if you have all the form inputs.
        //ddd($request->All());
        #Form Data individual fields can also be accessed via dynamic proprerties
        $totalAmount = $this->request->input('totalAmount');
        $tipPercentage = $this->request->input('tipPercentage');

        # Calculate the totalTip
        if ($tipPercentage == 'Being stingy') {
            $this->totalTip  = ($totalAmount * 10) / 100;
        }

        if ($tipPercentage == 'Average tip') {
            $this->totalTip = ($totalAmount * 15) / 100;
        }

        if ($tipPercentage == 'Feelin generous') {
            $this->totalTip = ($totalAmount * 20) / 100;
        }


        # get all input value from Form
        $totalAmount = floatval($this->request->input('totalAmount', null));
        $numberOfPeople = floatval($this->request->input('numberOfPeople', null));
        $roundUp = $this->request->input('roundUp');

        # Boolean to see if the request contains data for a particular field(roundUp)
        if ($this->request->has('roundUp')) {
            # If it has, round up the total amount.
            $splitAmount = round(($totalAmount + $this->totalTip) /$numberOfPeople);
        } else {
            $splitAmount =  ($totalAmount + $this->totalTip) / $numberOfPeople;
        }

        // dump($totalAmount);
        // dump($this->totalTip);
        // dump($splitAmount);

        #Redirect to the form View with the following variables
        return redirect()->back()->with([
            'totalAmount' => $totalAmount,
             'tipTotal' => $this->totalTip,
            'splitAmount' => $splitAmount

            ]);
    }
```

**I used the dump help function to view all variables to the page. I can display all the variables by using another view file. But for some odd reason, I am unable to pass them or redirect to the showForm view . Here is the error message that I got:**

```php
Facade\Ignition\Exceptions\ViewException
Undefined variable: splitAmount (View: /Applications/XAMPP/xamppfiles/htdocs/e15/p2/resources/views/showForm.blade.php)
http://e15p2.loc/

```

**my Github project link: https://github.com/nnoel2626/e15/tree/master/p2
Any help will be appreciated. Thanks.**

**Comment by kreinholz** [comment]
What happens if you change your redirect from what you currently have:

```php
return redirect()->back()->with([
            'totalAmount' => $totalAmount,
             'tipTotal' => $this->totalTip,
            'splitAmount' => $splitAmount

            ]);
```

To:

```php
return redirect('/')->with([
            'totalAmount' => $totalAmount,
             'tipTotal' => $this->totalTip,
            'splitAmount' => $splitAmount

            ]);
```

I'm just wondering if the **back()** method is causing trouble, even though reading the [documentation](https://laravel.com/docs/5.8/redirects#creating-redirects) I'm led to believe it should work.

Your **showForm.blade.php** file looks fine, since it has a conditional set re displaying $splitAmount:

```php
     @if(Session::has('splitAmount'))
     <fieldset>
         <div class='results alert alert-primary'>
            <ul>
            {{-- <li>{{ $splitAmount }}</li> --}}

            </ul>
        </div>
        </fieldset>
    @endif
```

That's the only thing that jumps out at me, but admittedly, I didn't try cloning your repository and running it locally. When I feel a bit more comfortable with my own progress on p2, I can do that and play around with it if you haven't gotten past this stumbling block by then. The fact the variables are displaying when you **dump** them to the page, or when you pass them to a different view, makes me think **back()** is somehow the culprit...

**Comment by nnoel2626** [comment]
This is how I had it originally:

```php
return redirect('/')->with([
            'totalAmount' => $totalAmount,
             'tipTotal' => $this->totalTip,
            'splitAmount' => $splitAmount

            ]);
```

**Comment by kreinholz** [comment]
In **TipController.php**, try initializing `$splitAmount` as a null variable prior to running your if/else conditional.

If that doesn't work, in **showForm.blade.php**, instead of `@if(Session::has('splitAmount'))` as a conditional, try `@if($splitAmount)` instead.

**Comment by nnoel2626** [comment]
Thank you so the help. I tried what you suggested but it did not work.

**Comment by budostylz** [comment]
I'm not at this stage yet with project 2. According to the validation notes, I think in order to pass form data via a custom redirect you have to use the withInput() function like below:

Susan's BookMark App
return redirect('/books/create')->withInput();

You might have to test if you can chain it with the 'with' function. Hopefully that might work. I'm about to build out the back end and test the same use case that you are having and can help to try to resolve this.

**Comment by nnoel2626** [comment]
Thank you all for the help but I was able to retrieve all the variables through Session data. In the view file I retrieved them like this: 

```php
{{ Session::get('splitAmount') }}
```

**Comment by nnoel2626** [comment]
I am still not sure why I was not able to display them in the form by using the Laravel blade syntax.
```
{{$splitAmount}}
```

**Comment by susanBuck** [comment]
Looks like this issue is resolved, but just wanted to add on some clarifying notes:

**Using the `with` method as part of a redirect will make data available via the session on subsequent page requests, but, an additional step is required to make it available for use in views.**

One way to do this is to extract the data from the session and then pass it to the view.

An example of this can be see in the search process in Bookmark...

In `BookController@search` we redirect back to `/` with the search results ([ref](https://github.com/susanBuck/e15/blob/master/bookmark/app/Http/Controllers/BookController.php#L90)):

```php
# Redirect back to the form with data/results stored in the session
# Ref: https://laravel.com/docs/redirects#redirecting-with-flashed-session-data
return redirect('/')->with([
    'searchTerms' => $searchTerms,
    'searchType' => $searchType,
    'searchResults' => $searchResults
]);
```

Then, in `PageController@welcome` we extract the data from the session and pass it to the view ([ref](https://github.com/susanBuck/e15/blob/master/bookmark/app/Http/Controllers/PageController.php#L12)):

```php
public function welcome()
{
    # Using the global `session` helper, we can extract our data that was 
    # passed from `BookController@search` as part of the redirect
    $searchTerms = session('searchTerms', null);
    $searchType = session('searchType', null);
    $searchResults = session('searchResults', null);

    # Return the view, making the above data available for use in the video
    return view('pages.welcome')->with([
        'searchTerms' => $searchTerms,
        'searchType' => $searchType,
        'searchResults' => $searchResults
    ]);
}
```

Then, within the `pages.welcome` view, we can access that data via variables like `$searchTerms`, `$searchType`, `$searchResults`.

Alternatively, you can extract the data from the session directly in the view using the Session facade, which is the solution @nnoel2626 ended up landing on:

```php
{{ Session::get('searchTerms') }}`
```

You could also use the global `session` helper directly in the view:

```php
session('searchTerms')
```

**Comment by RGPhD** [comment]
I wish I would have seen this post before!  It took me a couple of hours to remember to add ```with```.
:)
Robelyn

**Comment by budostylz** [comment]
> I wish I would have seen this post before! It took me a couple of hours to remember to add `with`.
> :)
> Robelyn

Sometimes it's best to learn the hard way : )
