### ISSUE TITLE
Apache won't start

### ISSUE THREAD

**Issue by janenycxo** [susanBuck/e15-spring20#24]
I suspect many of us are occupied with planning/re-working our day to day caused by Covid-19, and I hope all are safe, doing well and frequently washing our hands and practicing caution.

While I played around with P2 the last several days, today I sat down in hopes to figure this out, and coming short.

While working on my P2, the project deployed as it should until a commit rendered only the /index page. In my attempt to resolve that, subsequent committs returned either a blank page or a non-secure warning. Troubleshooting clues from notes brought me to updating composer (7.3.x updated to 7.4.x).

Upon doing so, Apache on xampp stopped running. I ruled out port conflicts (tried changing Listener to 81 and 888, and following with changing 443 to 4433 in the config files). 

I have created a p2a to test,and then deleted and restarted p2. 

I have attached a screenshot of the error message I receive from xampp, as well as the error details from the log file. Searching the storage/logs on visual studio only contains .gitignore. I have also tried the settings from repository to adjust the github pages to enforce https but that did not make a difference.

I really would like to get this issue fixed and get apache up and running to complete P2. Aside from uninstalling and reinstalling, is there another work around I could try?

[Apache Error.docx](https://github.com/susanBuck/e15-spring20/files/4347056/Apache.Error.docx)
[Apache Log.docx](https://github.com/susanBuck/e15-spring20/files/4347152/Apache.Log.docx)

**Comment by janenycxo** [comment]
I uninstalled (backing up the necessary files) and downloaded the latest version of xampp and apache successfully restarted.

http://e15p2.janenycxo.me/ is still returning a blank. I then tried to update the route to display text, and the page is still blank. However going to http://e15p2.loc/ will now display:

  | Name | Last modified | Size | Description
-- | -- | -- | -- | --

  | app/ | 2020-03-18 12:33 | - |  
  | artisan | 2020-03-18 12:33 | 1.7K |  
  | bootstrap/ | 2020-03-18 12:33 | - |  
  | composer.json | 2020-03-18 12:56 | 1.5K |  
  | composer.lock | 2020-03-18 12:33 | 187K |  
  | config/ | 2020-03-18 12:33 | - |  
  | database/ | 2020-03-18 12:33 | - |  
  | package.json | 2020-03-18 12:33 | 1.0K |  
  | phpunit.xml | 2020-03-18 12:33 | 1.1K |  
  | public/ | 2020-03-18 12:33 | - |  
  | resources/ | 2020-03-18 12:33 | - |  
  | routes/ | 2020-03-18 12:33 | - |  
  | server.php | 2020-03-18 12:33 | 584 |  
  | storage/ | 2020-03-18 12:33 | - |  
  | tests/ | 2020-03-18 12:33 | - |  
  | webpack.mix.js | 2020-03-18 12:33 | 553 |

**Comment by janenycxo** [comment]
Now Mysql stopped functioning...oy!

Good news...got the page running back on the local server (http://e15p2.loc/) . Still working on getting it to run on github pages(http://e15p2.janenycxo.me).

**Comment by RGPhD** [comment]
Hi @janenycxo ,

Hope you are keeping safe and healthy.  Is your local server **<http://e15p2.loc>** App functioning properly?

Robelyn

**Comment by RGPhD** [comment]
Hi again @janenycxo,

Did you set up your virtual host block again on **Digital Ocean** and ```git pull``` all updates to your production server?  

Oh, and don't forget to run ```$ composer install --no-dev``` and ```composer install --no-dev``` as instructed in @susanBuck's notes at <https://hesweb.dev/e15/notes/laravel/deploy-to-digital-ocean>. There were a lot of updates for composer.

Robelyn

**Comment by susanBuck** [comment]
Hi @janenycxo -

Catching up on this thread.

It sounds like the project on your local server is now functioning, yes?

And in my current test of your production server, http://e15p2.janenycxo.me is returning a blank white screen.

If you don't mind sharing access to your production server, I can help you troubleshoot this. [Details here on how to grant me access...](https://hesweb.dev/e15/notes/appendix/instructor-server-access)

**Comment by janenycxo** [comment]
> Hi @janenycxo ,
> 
> Hope you are keeping safe and healthy. Is your local server **http://e15p2.loc** App functioning properly?
> 
> Robelyn

Hi @RGPhD -thanks for chiming in!
I thought it might be an issue with routes but I have it directed to welcome while my local server is functioning.

**Comment by janenycxo** [comment]
> Hi @janenycxo -
> 
> Catching up on this thread.
> 
> It sounds like the project on your local server is now functioning, yes?
> 
> And in my current test of your production server, http://e15p2.janenycxo.me is returning a blank white screen.
> 
> If you don't mind sharing access to your production server, I can help you troubleshoot this. [Details here on how to grant me access...](https://hesweb.dev/e15/notes/appendix/instructor-server-access)

Hi @susanBuck,
I have added the public key, thank you for assisting!

**Comment by susanBuck** [comment]
@janenycxo Great - Logging in now! Will report back on what I find.

**Comment by susanBuck** [comment]
Hi @janenycxo -

I did some debugging on your production server and found that most of the steps in [Prep DigitalOcean for Laravel](https://hesweb.dev/e15/notes/laravel/prep-digital-ocean-for-laravel) and [Deploy Laravel app to DigitalOcean](https://hesweb.dev/e15/notes/laravel/deploy-to-digital-ocean) had not yet been completed.

The following is a summary of how I determined this and what I did to fix it:

+ The permissions on storage/logs was still `root` instead of `www-data` indicating the [permissions step](https://hesweb.dev/e15/notes/laravel/deploy-to-digital-ocean#permissions) was not completed
+ There was [no `vendor` directory ](https://hesweb.dev/e15/notes/laravel/deploy-to-digital-ocean#build-vendor-directory) indicating `composer install --no-dev` had not been run.
+ When I tried running `composer install --no-dev` it told me the command `composer` was not found, [indicating composer had not been installed on the server](https://hesweb.dev/e15/notes/laravel/prep-digital-ocean-for-laravel#install-composer).
+ After installing composer and running `composer install --no-dev`, there was an error noting *the requested PHP extension mbstring is missing from your system.* indicating the [necessary modules had not been installed/updated.](https://hesweb.dev/e15/notes/laravel/prep-digital-ocean-for-laravel#installupdate-necessary-modules). After installing them, I was able to run `composer install --no-dev` to build the `vendor` directory.
+ There was no [`.env` file in the root of the project](https://hesweb.dev/e15/notes/laravel/deploy-to-digital-ocean#environment-file-env-on-production) so I created that and then [generated the APP_KEY](https://hesweb.dev/e15/notes/laravel/deploy-to-digital-ocean#app-key)
+ I double checked the [subdomain settings](https://hesweb.dev/e15/notes/laravel/deploy-to-digital-ocean#configure-subdomain) and corrected them so that `e15p2.janenycxo.me` was pointing to `/var/www/html/e15/p2/public` instead of `/var/www/html/e15/p2`.

After the above checks/fixes, the site would load but with a 500 server error:

![image](https://user-images.githubusercontent.com/237711/77099293-0f689f80-69ea-11ea-9f5a-d63b1400e918.png)


To track this bug down, I looked to your error log file `/var/www/html/e15/p2/storage/logs/laravel.log` for clues and found this error:

```
[2020-03-19 17:50:29] production.ERROR: Target class [App\Http\Controllers\homePage] does not exist. {"exception":"[object] (Illuminate\\Contracts\\Container\\BindingResolutionException(code: 0): Target class [App\\Http\\Controllers\\homePage] does not exist. at /var/www/html/e15/p2/vendor/laravel/framework/src/Illuminate/Container/Container.php:805)
[stacktrace]
#0 /var/www/html/e15/p2/vendo
```

This error made reference to targeting a controller class, so I opened up your routes file (`/routes/web.php`) to see what routes were triggering which controllers. There I found this route:

```
# Homepage
Route::get('/', 'homePage@index');
```

This is attempting to load a controller `homePage` [which does not exist](https://github.com/janenycxo/e15/tree/master/p2/app/Http/Controllers).

I didn't want to start changing code on your production server to address this. It's better that you debug this locally, get it working there, then push the changes to production and confirm it's also working there.

Please let me know if you run into any walls getting this resolved locally.

**Comment by janenycxo** [comment]
i realize many steps are involved and confused myself along the way. The very first version of p2 worked as it should until apache crashed, and i deleted p2 entirely. I then re-installed composer, along with xampp to have the latest versions (thinking that might resolve any incompatibilities)...I started to re-work p2 along with renaming controller because files were deleted during install, I had a clean working p2. I am going to review what you have provided, and hope to fix P2. I am certain I will have further questions, but thank you for now! ;)

**Comment by susanBuck** [comment]
Totally understand. : ) Going to close this thread just to keep the issues organized, so feel free to start a new one as you continue your dev process!
