### ISSUE TITLE
Error running migration - Specified key was too long

### ISSUE THREAD

**Issue by anyav77** [susanBuck/e15-spring20#30]
I ran the migration, but the books table wasn't created.
``` git
C:\xampp\htdocs\e15\bookmark (master){hg}
λ php artisan make:migration create_books_table
Created Migration: 2020_04_01_000137_create_books_table

warning: LF will be replaced by CRLF in bookmark/routes/web.php.
The file will have its original line endings in your working directory
C:\xampp\htdocs\e15\bookmark (master){hg}
λ php artisan migrate
Migration table created successfully.
Migrating: 2014_10_12_000000_create_users_table

   Illuminate\Database\QueryException  : SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: alter table `users` add unique `users_email_unique`(`email`))

  at C:\xampp\htdocs\e15\bookmark\vendor\laravel\framework\src\Illuminate\Database\Connection.php:669
    665|         // If an exception occurs when attempting to run a query, we'll format the error
    666|         // message to include the bindings with SQL, which will make this exception a
    667|         // lot more helpful to the developer instead of just the database's errors.
    668|         catch (Exception $e) {
  > 669|             throw new QueryException(
    670|                 $query, $this->prepareBindings($bindings), $e
    671|             );
    672|         }
    673|

  Exception trace:

  1   PDOException::("SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes")
      C:\xampp\htdocs\e15\bookmark\vendor\laravel\framework\src\Illuminate\Database\Connection.php:463

  2   PDOStatement::execute()
      C:\xampp\htdocs\e15\bookmark\vendor\laravel\framework\src\Illuminate\Database\Connection.php:463

  Please use the argument -v to see more details.

warning: LF will be replaced by CRLF in bookmark/routes/web.php.
The file will have its original line endings in your working directory
C:\xampp\htdocs\e15\bookmark (master){hg}
λ
```
I tried migrate:fresh, but the error reoccurs.
![screenshot-migration issue](https://user-images.githubusercontent.com/1045307/78089865-6b81db00-737d-11ea-83e7-34050152b03f.png)

**Comment by anyav77** [comment]
Could it possibly be a version issue?  I haven't updated to Laravel 7.

**Comment by susanBuck** [comment]
I don't believe it's a Laravel 6 vs. 7 issue because it worked in my Bookmark app which is also running v6.

The key clue is this error:
```
SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: alter table `users` add unique `users_email_unique`(`email`))
```

It has to do with the storage limits on key/index fields. 

Here is an explanation from the Laravel docs:

> Index Lengths & MySQL / MariaDB
> Laravel uses the utf8mb4 character set by default, which includes support for storing "emojis" in the database. If you are running a version of MySQL older than the 5.7.7 release or MariaDB older than the 10.2.2 release, you may need to manually configure the default string length generated by migrations in order for MySQL to create indexes for them. -https://laravel.com/docs/master/migrations/#creating-indexes.

On my XAMPP, I'm seeing MariaDB version `10.4.11` so it wasn't an issue.

If you go to http://localhost/phpmyadmin and look in the **Database server** panel on the right you can see what version of MariaDB you're running. If it's older than 10.2.2, that's the problem.

![image](https://user-images.githubusercontent.com/237711/78090597-90377c00-7398-11ea-9b88-40a7528bf935.png)

To address it you can either update XAMPP to update MariaDB - or in `/app/Providers/AppServiceProvider.php` update the `boot` method adding the following Schema line:

```php
public function boot()
{
    \Schema::defaultStringLength(191);
}
```

This will restrict your key lengths avoiding the problem.

**IMPORTANT NOTE:** if you decide to go the route up updating XAMPP you want to first backup the files/directories I outline here: [Updating XAMPP ](https://hesweb.dev/e15/notes/local-server/xampp-windows#updating-xampp-fyi-for-returning-students).

**Comment by RGPhD** [comment]
Dear @anyav77 and Professor @susanBuck,

I had the exact same error message on the first run of ```php artisan migrate```. 

After adding the ```boot code```, I deleted the migrations and users table in my bookmark database, ran ```php artisan migrate``` again, and it worked.

Thank you,

Robelyn

**Comment by anyav77** [comment]
I added the code and ran 'php artisan migrate:fresh' command, and it worked.
Thank you!
