### ISSUE TITLE
Updating XAMPP

### ISSUE THREAD

**Issue by kreinholz** [susanBuck/e15-spring20#32]
I took E-28 last semester, and stuck with the older version of XAMPP I installed at the beginning of the Fall 2019 semester (version 7.3.1).

I'm now going through the process of updating XAMPP, which Week 9's lectures inspired me to finally do.

I noticed, however, that the [download link](https://www.apachefriends.org/xampp-files/7.4.1/xampp-windows-x64-7.4.1-1-VC15-installer.exe) provided in the [Notes](https://hesweb.dev/e15/notes/local-server/xampp-windows) is no longer the current version (the Notes provide a download link to version 7.4.1). I found that by visiting [Apache Friends](https://www.apachefriends.org/index.html) and selecting my platform (Windows).

The current version appears to be 7.4.4, and for Windows users the download link is [here](https://www.apachefriends.org/xampp-files/7.4.4/xampp-windows-x64-7.4.4-0-VC15-installer.exe). I'm going to try using the latest version of XAMPP and assume, since it's not even a minor version update from the version linked to in the Notes for this semester, but just a patch version update, there shouldn't be any show stoppers.

Still, this got me thinking...how often would it be advisable to update XAMPP? For the remainder of this semester, I don't see needing to update XAMPP, but beyond? It seems advisable to update at least occasionally. It's a shame the /htdocs directory and two config files have to be manually backed up and restored as part of the update process, but it's not that bad in the grand scheme of things, especially if we're getting bug fixes and patches against security vulnerabilities.

**Comment by susanBuck** [comment]
I agree you shouldn't run into any show stoppers when grabbing the latest.

I always link to the latest version "as of this writing" in the notes at the beginning of the semester to try and into that version throughout the semester, even if XAMPP updates. This is just to create consistency with what software we're all using.

Before I used to do this, sometimes students would install an updated version later in the semester, and suddenly run into some differences.

But - like you said - this is just a patch version update - so I don't anticipate any problems.

In terms of how often I would advise updating XAMPP - 

I tend to do it at the start of every semester (assuming there is an update), just because I want to set students up with the latest version.

If I wasn't teaching, I would probably wait to update until:

1. They added a feature/change that was enticing enough to make me want to update : )
2. Something about the current version I was using became incompatible with something I was trying to do in my apps
3. The update involved some notable security/bug fix

Let me know if you run into hiccups during/post update - especially if it's something that conflicts with any of instructions/procedures we're following. : )

**Comment by kreinholz** [comment]
Upgrade went smoothly! Only caveat is after running the xampp uninstaller.exe program, it was necessary to manually delete C:\xampp\, which had some leftover empty directories inside of it. Once I did that, the [update instructions in the course notes](https://hesweb.dev/e15/notes/local-server/xampp-windows#updating-xampp-fyi-for-returning-students) worked perfectly. All of my E-15 apps seem to be running smoothly on my local environment with the updated XAMPP.

**Comment by budostylz** [comment]
Thanks for the insight Kevin. This gives me a fresh perspective of not just considering the framework but the complete architecture as a whole.

**Comment by kreinholz** [comment]
On a side note, I came across a PHP memory issue in version 7.3.1, what I installed at the beginning of E-28 last Fall, that is corrected at least as of version 7.4.4 (and probably 7.4.1, the version folks would've installed at the beginning of this semester for E-15), while working on my independent-study project. Another good reason to upgrade! :)
