### ISSUE TITLE
Database Design Conventions

### ISSUE THREAD

**Issue by budostylz** [susanBuck/e15-spring20#34]
Focusing on column conventions regarding primary and foreign key names. I have two tables, bars and bartenders. Table bartenders have an ID column name ‘id’ which is the primary key. Table bartenders also have a foreign key name ‘bar_id’ which points to the ID column in bars. I don’t want to rename ‘bar_id’ to ‘id’ in tables bartender. Am I not following convention for this use case since the ID column name is pretty generic?

**Comment by susanBuck** [comment]
column `bar_id` in table `bar` does not need to be named `id` because it is not a **primary** key.

Instead, it's a **foreign** key, and the convention with foreign keys (as you've correctly done) is to use the name of the table you're connecting to (in this case, `bar`) and append `_id`... resulting in `bar_id`. 

So your tables would end up looking like this:

**Table `bars`**
+ `id` (primary key)
+ ...etc...

**Table: `bartenders`**
+ `id` (primary key)
+ `bar_id` (foreign key connecting to `bars` table)
+ ...etc...

_Side note for anyone reading this thread - we'll talk about table relationships and foreign keys in Week 11 : )_

**Comment by budostylz** [comment]
Awesome, making sure I’m staying within database design conventions. Thanks a bunch Susan.
V/r, Shaun

**Comment by budostylz** [comment]
Fat fingered the close button. LoL!

**Comment by susanBuck** [comment]
np! : ) Closing this thread, but feel free to re-open or start a new thread if you have additional db convention questions!
