### ISSUE TITLE
findBySlug($slug) 

### ISSUE THREAD

**Issue by anyav77** [susanBuck/e15-spring20#62]
I've been trying to use  $book = $user->books()->findBySlug($slug);
similar to $book = Book::findBySlug($slug);

However, I'm getting an error:
Call to undefined method Illuminate\Database\Eloquent\Relations\BelongsToMany::findBySlug()

What am I doing wrong?

**Comment by nnoel2626** [comment]
FindBySlug is a defined method in the Book model. Do you have such a method in your Book model?

**Comment by susanBuck** [comment]
When you invoke `$user->books()` it returns a BelongsToMany relationship object, that gives you access to methods for working with that relationship.

Ex:
```php
$booksRelationship = $user->books();
dump($booksRelationship);
```

Yields:
![image](https://user-images.githubusercontent.com/237711/81496702-7e929f80-9287-11ea-8605-ab3d3d0073a6.png)

This BelongsToMany relationship object is not a Book object, and so it does not have access to Book's `findBySlug` method.

To get to Book objects from a relationship, treat the relationship `books` as a dynamic property instead of invoking it as a method. E.g.:

```php
$usersBooks = $user->books;
```

Of course, this does return a Collection of Books so you have to go a step further to get to individual Book objects.

For example, we can drill down to the first Book in the collection - and upon that we can then invoke `findBySlug`:

```php
$usersBooks = $user->books;
$exampleBook = $usersBooks->first();
dump($exampleBook->findBySlug('the-martian')->toArray());
```

Or, we could iterate through the Collection and get to each Book:

```php
$usersBooks = $user->books;
foreach ($usersBooks as $book) {
    dump($book->findBySlug('the-martian')->toArray());
}
```

But neither of these examples quite make sense - `findBySlug` is designed to find a book object we don't yet have - in the above examples, we've already queried for the book objects.

I'm trying to think in what context you'd want to use `findBySlug` with a relationship like this - maybe if you want to determine if a certain book is in a user's "list" ?

If so, I'd suggest filtering on the collection like so:

```php
$usersBooks = $user->books;

$results = $usersBooks->filter(function ($book, $key) {
    return $book->slug == 'harry-potter-and-the-chamber-of-secrets';
});

dump($results);

if (count($results) > 0) {
    dump("harry-potter-and-the-chamber-of-secrets is in this user's list");
}
```

Ref: https://laravel.com/docs/7.x/collections#method-filter

Let me know if that's similar to what you're trying to accomplish. If not, we can think of another solution.

**Comment by susanBuck** [comment]
Closing this thread as I believe the question is answered - but don't hesitate to re-open or keep the discussion going if there are any follow-up questions.
