### ISSUE TITLE
Browser test for adding a resource error

### ISSUE THREAD

**Issue by nnoel2626** [susanBuck/e15-spring20#69]
I keep getting this error message below when I try to run the "testAddingMicrophone" test. I followed the instructions that Susan provided for adding a book to the list. Does anybody know how to fix this problem?

```PHP

 Tests\Browser\MicrophonesTest::testAddingMicrophone
Facebook\WebDriver\Exception\JavascriptErrorException: javascript error: Cannot set property 'value' of null
  (Session info: chrome=81.0.4044.138)
```

**Comment by susanBuck** [comment]
```
Cannot set property 'value' of null
```

Usually this means you're trying to select something on the page but it's not found (it's null - and thus you can't set the value of a null element).

When I try to run your `MicrophonesTest` I don't get that error - instead I get these errors:

```
1) Tests\Browser\MicrophonesTest::testLoadingMicrophoneWithTags
Illuminate\Database\QueryException: SQLSTATE[HY000]: General error: 1364 Field 'slug' doesn't have a default value (SQL: insert into `microphones` (`updated_at`, `created_at`) values (2020-05-12 01:23:03, 2020-05-12 01:23:03))
```

This happens because that test is invoking your MicrophoneFactory which looks incomplete - it's not setting any of the fields, including slug:

```php
$factory->define(Microphone::class, function (Faker $faker) {
    return [
        //
    ];
});
```


Next error:
```
2) Tests\Browser\MicrophonesTest::testLoadingMicrophoneWithNoAuthor
InvalidArgumentException: Unable to locate [withUser] state for [App\Microphone].
```

This error happens because in the test you invoke the Microphone factory again, this time with the states `withuser` and `withoutAuthor`

```
$microphone = factory(Microphone::class)->states('withUser', 'withoutAuthor')->create();
```

I think maybe this is leftover/unedited code from the lecture example since it references author?
