### ISSUE TITLE
Middlewear redirect for login link

### ISSUE THREAD

**Issue by anyav77** [susanBuck/e15-spring20#70]
I decided to try built-in middleware functionality, to use the default /home path for user dashboard.
I also tried Auth::user(), following the class notes.

Now with two systems installed, I'm getting an error on accessing login:
http://e15p3.loc/login
`[http://e15p3.atozez.com/login](http://e15p3.atozez.com/login)`

> This page isn’t working
> e15p3.loc redirected you too many times.
> Try clearing your cookies.
> ERR_TOO_MANY_REDIRECTS

What do you recommend?  
Did I cause a conflict, or is there another issue?

**Comment by susanBuck** [comment]
I see you have `Auth::routes` in the auth middleware group in your routes file:

![image](https://user-images.githubusercontent.com/237711/81665851-3dc59280-940f-11ea-969a-adb23abf9bfb.png)

With that in place, if you run `php artisan route:list` to see your routes, note that the `/login` route has both a `guest` and `auth` route applied to it:

![image](https://user-images.githubusercontent.com/237711/81666786-7ca81800-9410-11ea-818a-acce1b8daa0c.png)

This is causing the redirect loop which results in the error you're seeing. It's because `auth` and `guest` are basically trying to cancel each other out - `auth` is saying the visitor must be logged in, while `guest` is saying they must not.

Try moving `Auth::routes` out of your auth middleware group - it will put each auth-specific route in the appropriate middleware for you. 

Here's the route list after moving it:

![image](https://user-images.githubusercontent.com/237711/81667095-de688200-9410-11ea-92e7-e7694bd27b65.png)

**Comment by anyav77** [comment]
Thank you so much!  It helped on the local server.

I tried to push the changes to the production, but it's not updating.
I get the message in the composer: already up to date.  I ran pull and composer update a few times:

```git
root@e2:~# cd /var/www/html/e15
root@e2:/var/www/html/e15# git pull
Already up to date.
root@e2:/var/www/html/e15# composer install --no-dev
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Composer could not find a composer.json file in /var/www/html/e15
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
root@e2:/var/www/html/e15# cd p3
root@e2:/var/www/html/e15/p3# git pull
Already up to date.
root@e2:/var/www/html/e15/p3# composer install --no-dev
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Installing dependencies from lock file
Nothing to install or update
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
Discovered Package: fideloper/proxy
Discovered Package: fruitcake/laravel-cors
Discovered Package: laravel/tinker
Discovered Package: laravel/ui
Discovered Package: nesbot/carbon
Package manifest generated successfully.
1 package you are using is looking for funding.
Use the composer fund command to find out more!
root@e2:/var/www/html/e15/p3# git pull
Already up to date.
root@e2:/var/www/html/e15/p3# cd ../
root@e2:/var/www/html/e15# git pull
Already up to date.
```

**Comment by anyav77** [comment]
Please disregard the previous comment: I didn't finish push on the local server.

It's working now.
